# Generated by Django 5.0.4 on 2026-07-04 23:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail Institucional')),
                ('registration_number', models.CharField(max_length=30, unique=True, verbose_name='Matrícula')),
                ('employee_type', models.CharField(choices=[('EMPLOYEE', 'Empregado'), ('COLLABORATOR', 'Colaborador')], default='EMPLOYEE', max_length=20, verbose_name='Tipo de Vínculo')),
                ('profile_role', models.CharField(choices=[('REQUESTER', 'Solicitante'), ('SUPERVISOR', 'Supervisor'), ('TRAVEL_ANALYST', 'Analista de Viagens'), ('FINANCE', 'Financeiro (SOF)'), ('DIRECTOR', 'Diretor / Ordenador'), ('ADMIN', 'Administrador')], default='REQUESTER', max_length=20, verbose_name='Papel no Sistema')),
                ('unit', models.CharField(blank=True, max_length=100, verbose_name='Unidade (UG)')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='Setor')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='users.userprofile', verbose_name='Supervisor Imediato')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'db_table': 'user_profiles',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['profile_role'], name='user_profil_profile_13a65d_idx'), models.Index(fields=['registration_number'], name='user_profil_registr_d173eb_idx')],
            },
        ),
    ]
