# Generated by Django 5.0.4 on 2026-07-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_role',
            field=models.CharField(choices=[('REQUESTER', 'Solicitante'), ('SUPERVISOR', 'Supervisor'), ('TRAVEL_ANALYST', 'Analista de Viagens'), ('FINANCE', 'Financeiro (SOF)'), ('CHADM', 'CHADM (Recursos)'), ('SIL', 'SIL (Frota/Transporte)'), ('DIRECTOR', 'Diretor / Ordenador'), ('ADMIN', 'Administrador')], default='REQUESTER', max_length=20, verbose_name='Papel no Sistema'),
        ),
    ]
