# Generated by Django 5.0.4 on 2026-07-12 02:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorecido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome')),
                ('registration_number', models.CharField(blank=True, max_length=30, verbose_name='Matrícula')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('unit', models.CharField(blank=True, max_length=120, verbose_name='Unidade')),
                ('position', models.CharField(blank=True, max_length=120, verbose_name='Cargo')),
                ('chief_name', models.CharField(blank=True, max_length=200, verbose_name='Chefe (Ordenador)')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('bank_info', models.CharField(blank=True, max_length=120, verbose_name='Dados Bancários')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Favorecido (SAGU)',
                'verbose_name_plural': 'Favorecidos (SAGU)',
                'db_table': 'favorecidos',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='favorecidos_full_na_1faeaf_idx'), models.Index(fields=['registration_number'], name='favorecidos_registr_2a9956_idx')],
            },
        ),
    ]
