# Generated by Django 5.0.4 on 2026-07-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorecido',
            name='person_type',
            field=models.CharField(choices=[('EMPLOYEE', 'Empregado'), ('COLLABORATOR', 'Colaborador')], default='EMPLOYEE', max_length=20, verbose_name='Vínculo'),
        ),
    ]
