# Generated by Django 5.0.4 on 2026-07-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_favorecido_person_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorecido',
            name='blocked',
            field=models.BooleanField(default=False, verbose_name='Bloqueado (inadimplente)'),
        ),
        migrations.AddField(
            model_name='favorecido',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motivo do Bloqueio'),
        ),
    ]
