/**
 * aeroportos.js — Aeroportos do Brasil (código IATA — Cidade/UF — Aeroporto).
 * Usado como lista de busca nos campos Origem/Destino das Passagens Aéreas.
 */
export const AEROPORTOS = [
  'GRU — São Paulo/SP (Guarulhos)',
  'CGH — São Paulo/SP (Congonhas)',
  'VCP — Campinas/SP (Viracopos)',
  'GIG — Rio de Janeiro/RJ (Galeão)',
  'SDU — Rio de Janeiro/RJ (Santos Dumont)',
  'BSB — Brasília/DF (Pres. Juscelino Kubitschek)',
  'CNF — Belo Horizonte/MG (Confins)',
  'PLU — Belo Horizonte/MG (Pampulha)',
  'SSA — Salvador/BA (Dep. Luís Eduardo Magalhães)',
  'REC — Recife/PE (Guararapes - Gilberto Freyre)',
  'FOR — Fortaleza/CE (Pinto Martins)',
  'POA — Porto Alegre/RS (Salgado Filho)',
  'CWB — Curitiba/PR (Afonso Pena)',
  'CGB — Cuiabá/MT (Marechal Rondon)',
  'CGR — Campo Grande/MS (Campo Grande)',
  'BEL — Belém/PA (Val de Cans)',
  'MAO — Manaus/AM (Eduardo Gomes)',
  'NAT — Natal/RN (Aluízio Alves)',
  'JPA — João Pessoa/PB (Castro Pinto)',
  'MCZ — Maceió/AL (Zumbi dos Palmares)',
  'AJU — Aracaju/SE (Santa Maria)',
  'THE — Teresina/PI (Sen. Petrônio Portella)',
  'SLZ — São Luís/MA (Marechal Cunha Machado)',
  'GYN — Goiânia/GO (Santa Genoveva)',
  'VIX — Vitória/ES (Eurico de Aguiar Salles)',
  'FLN — Florianópolis/SC (Hercílio Luz)',
  'PMW — Palmas/TO (Palmas)',
  'PVH — Porto Velho/RO (Gov. Jorge Teixeira)',
  'RBR — Rio Branco/AC (Plácido de Castro)',
  'BVB — Boa Vista/RR (Atlas Brasil Cantanhede)',
  'MCP — Macapá/AP (Alberto Alcolumbre)',
  'IGU — Foz do Iguaçu/PR (Cataratas)',
  'NVT — Navegantes/SC (Ministro Victor Konder)',
  'JOI — Joinville/SC (Lauro Carneiro de Loyola)',
  'LDB — Londrina/PR (Gov. José Richa)',
  'MGF — Maringá/PR (Sílvio Name Júnior)',
  'UDI — Uberlândia/MG (Ten. Cel. Av. César Bombonato)',
  'RAO — Ribeirão Preto/SP (Leite Lopes)',
  'SJP — São José do Rio Preto/SP (Prof. Eribelto Manoel Reino)',
  'IOS — Ilhéus/BA (Jorge Amado)',
  'PNZ — Petrolina/PE (Sen. Nilo Coelho)',
  'JDO — Juazeiro do Norte/CE (Orlando Bezerra de Menezes)',
  'IMP — Imperatriz/MA (Prefeito Renato Moreira)',
  'STM — Santarém/PA (Maestro Wilson Fonseca)',
  'CXJ — Caxias do Sul/RS (Hugo Cantergiani)',
  'MAB — Marabá/PA (João Correa da Rocha)',
  'PMG — Ponta Porã/MS',
  'DOU — Dourados/MS',
  'CZS — Cruzeiro do Sul/AC',
  'BPS — Porto Seguro/BA',
  'MOC — Montes Claros/MG (Mário Ribeiro)',
  'JJD — Jericoacoara/CE',
];
