# Generated by Django 5.0.4 on 2026-07-05 00:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel_requests', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('plate', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('model', models.CharField(max_length=100, verbose_name='Modelo')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano')),
                ('is_cargo', models.BooleanField(default=False, verbose_name='Carga')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'fleet_vehicles',
                'ordering': ['plate'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('cnh_number', models.CharField(max_length=20, verbose_name='CNH')),
                ('cnh_expiry', models.DateField(verbose_name='Validade da CNH')),
                ('is_embrapa', models.BooleanField(default=True, help_text='Desmarcado = terceirizado / SLT', verbose_name='Motorista da Embrapa')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_records', to='users.userprofile', verbose_name='Usuário Vinculado')),
            ],
            options={
                'verbose_name': 'Motorista',
                'verbose_name_plural': 'Motoristas',
                'db_table': 'fleet_drivers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fleet.driver', verbose_name='Motorista')),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='travel_requests.travelrequest', verbose_name='Viagem')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fleet.vehicle', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Alocação de Veículo',
                'verbose_name_plural': 'Alocações de Veículos',
                'db_table': 'fleet_assignments',
            },
        ),
    ]
