# Generated by Django 5.0.4 on 2026-07-11 23:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
        ('travel_requests', '0003_resourceline_sponsor_researchproject_is_external_and_more'),
        ('users', '0002_alter_userprofile_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRequisition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('number', models.CharField(blank=True, max_length=25, unique=True, verbose_name='Número da Requisição')),
                ('estimated_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM Estimada')),
                ('route', models.CharField(blank=True, max_length=255, verbose_name='Trajeto')),
                ('objective', models.TextField(blank=True, verbose_name='Objetivo')),
                ('needs_driver', models.BooleanField(default=False, verbose_name='Necessita Motorista?')),
                ('requester_is_driver', models.BooleanField(default=False, verbose_name='Cliente será o Motorista?')),
                ('actual_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='KM Real')),
                ('negation_reason', models.TextField(blank=True, verbose_name='Motivo da Negativa')),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitada'), ('CHADM_REVIEW', 'Em análise (CHADM)'), ('NEGATED', 'Negada'), ('AT_SIL', 'Remetida ao SIL'), ('RESERVED', 'Reservada'), ('IN_USE', 'Em uso'), ('CLOSED', 'Fechada'), ('CANCELLED', 'Cancelada')], default='REQUESTED', max_length=20, verbose_name='Status')),
                ('assignment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition', to='fleet.vehicleassignment', verbose_name='Alocação (Veículo/Motorista)')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_requisitions', to='users.userprofile', verbose_name='Solicitante')),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_requisitions', to='travel_requests.travelrequest', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Requisição de Veículo',
                'verbose_name_plural': 'Requisições de Veículos',
                'db_table': 'fleet_requisitions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='fleet_requi_status_17d441_idx'), models.Index(fields=['travel_request'], name='fleet_requi_travel__8951b6_idx')],
            },
        ),
    ]
