# Generated by Django 5.0.4 on 2026-07-11 23:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehiclerequisition'),
        ('users', '0002_alter_userprofile_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('kind', models.CharField(choices=[('INITIAL', 'Saída (vistoria prévia)'), ('FINAL', 'Retorno')], max_length=10, verbose_name='Momento')),
                ('km', models.PositiveIntegerField(blank=True, null=True, verbose_name='Odômetro (KM)')),
                ('fuel_level', models.CharField(blank=True, choices=[('RESERVE', 'Reserva'), ('QUARTER', '1/4'), ('HALF', '1/2'), ('THREE_QUARTER', '3/4'), ('FULL', 'Cheio')], max_length=15, verbose_name='Nível de Combustível')),
                ('tires_ok', models.BooleanField(default=True, verbose_name='Pneus e estepe OK')),
                ('lights_ok', models.BooleanField(default=True, verbose_name='Faróis e lanternas OK')),
                ('documents_ok', models.BooleanField(default=True, verbose_name='Documentos (CRLV) OK')),
                ('extinguisher_ok', models.BooleanField(default=True, verbose_name='Extintor OK')),
                ('cleanliness_ok', models.BooleanField(default=True, verbose_name='Limpeza OK')),
                ('damages', models.TextField(blank=True, verbose_name='Avarias Observadas')),
                ('observations', models.TextField(blank=True, verbose_name='Observações')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_checklists', to='users.userprofile', verbose_name='Vistoriado por')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='fleet.vehiclerequisition', verbose_name='Requisição')),
            ],
            options={
                'verbose_name': 'Check-list de Veículo',
                'verbose_name_plural': 'Check-lists de Veículos',
                'db_table': 'fleet_checklists',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='vehiclechecklist',
            constraint=models.UniqueConstraint(fields=('requisition', 'kind'), name='uniq_checklist_por_requisicao_e_tipo'),
        ),
    ]
