# Generated by Django 5.0.4 on 2026-07-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_vehiclechecklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclerequisition',
            name='passengers',
            field=models.TextField(blank=True, help_text='Nomes das pessoas que viajam neste veículo (ex.: viagem coletiva).', verbose_name='Passageiros (mesmo veículo)'),
        ),
    ]
