# Generated by Django 5.0.4 on 2026-07-04 23:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('city', models.CharField(max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('country', models.CharField(default='Brasil', max_length=100, verbose_name='País')),
                ('is_international', models.BooleanField(default=False, verbose_name='Internacional')),
                ('daily_rate_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diária Específica (R$)')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'db_table': 'destinations',
                'ordering': ['country', 'state', 'city'],
                'indexes': [models.Index(fields=['is_international'], name='destination_is_inte_5366e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='TravelRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('request_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número da Solicitação')),
                ('employee_type', models.CharField(choices=[('EMPLOYEE', 'Empregado'), ('COLLABORATOR', 'Colaborador')], max_length=20, verbose_name='Tipo de Vínculo')),
                ('cost_type', models.CharField(choices=[('EMBRAPA_COST', 'Ônus para Embrapa'), ('NO_EMBRAPA_COST', 'Sem Ônus para Embrapa')], default='EMBRAPA_COST', max_length=20, verbose_name='Tipo de Ônus')),
                ('origin_city', models.CharField(max_length=100, verbose_name='Cidade de Origem')),
                ('origin_state', models.CharField(blank=True, max_length=2, verbose_name='UF de Origem')),
                ('departure_date', models.DateField(verbose_name='Data de Saída')),
                ('return_date', models.DateField(verbose_name='Data de Retorno')),
                ('objective', models.TextField(verbose_name='Objetivo da Viagem')),
                ('project_code', models.CharField(blank=True, max_length=50, verbose_name='Código do Projeto')),
                ('funding_source', models.CharField(blank=True, max_length=200, verbose_name='Fonte de Recursos')),
                ('needs_flights', models.BooleanField(default=False, verbose_name='Solicita Passagens Aéreas')),
                ('needs_daily_allowance', models.BooleanField(default=False, verbose_name='Solicita Diárias')),
                ('daily_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Quantidade de Diárias')),
                ('estimated_daily_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Estimado de Diárias (R$)')),
                ('needs_accommodation', models.BooleanField(default=False, verbose_name='Necessita Hospedagem')),
                ('accommodation_notes', models.TextField(blank=True, verbose_name='Obs. Hospedagem')),
                ('other_expenses_description', models.TextField(blank=True, verbose_name='Outras Despesas')),
                ('other_expenses_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Outras Despesas (R$)')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Submetida'), ('UNDER_REVIEW', 'Em Análise'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Concluída')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submetida em')),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='travel_requests', to='travel_requests.destination', verbose_name='Destino')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='travel_requests', to='users.userprofile', verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação de Viagem',
                'verbose_name_plural': 'Solicitações de Viagem',
                'db_table': 'travel_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('authorization_level', models.IntegerField(default=1, verbose_name='Nível de Autorização')),
                ('decision', models.CharField(choices=[('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado'), ('PENDING', 'Pendente')], default='PENDING', max_length=10, verbose_name='Decisão')),
                ('justification', models.TextField(blank=True, verbose_name='Justificativa')),
                ('digital_signature_hash', models.CharField(blank=True, max_length=255, verbose_name='Assinatura Digital')),
                ('authorized_at', models.DateTimeField(blank=True, null=True, verbose_name='Autorizado em')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('authorizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations_given', to='users.userprofile', verbose_name='Autorizador')),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorizations', to='travel_requests.travelrequest', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Autorização de Viagem',
                'verbose_name_plural': 'Autorizações de Viagem',
                'db_table': 'travel_authorizations',
                'ordering': ['-authorized_at'],
            },
        ),
        migrations.AddIndex(
            model_name='travelrequest',
            index=models.Index(fields=['status'], name='travel_requ_status_2018b9_idx'),
        ),
        migrations.AddIndex(
            model_name='travelrequest',
            index=models.Index(fields=['employee_type'], name='travel_requ_employe_70d192_idx'),
        ),
        migrations.AddIndex(
            model_name='travelrequest',
            index=models.Index(fields=['cost_type'], name='travel_requ_cost_ty_6f0dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='travelrequest',
            index=models.Index(fields=['departure_date', 'return_date'], name='travel_requ_departu_5b9821_idx'),
        ),
        migrations.AddIndex(
            model_name='travelrequest',
            index=models.Index(fields=['requester'], name='travel_requ_request_b3900e_idx'),
        ),
    ]
