# Generated by Django 5.0.4 on 2026-07-05 00:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingAgency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('acronym', models.CharField(blank=True, max_length=30, verbose_name='Sigla')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Agência de Fomento',
                'verbose_name_plural': 'Agências de Fomento',
                'db_table': 'funding_agencies',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='modality',
            field=models.CharField(blank=True, help_text='Ex.: Transporte de pessoas fora do município com veículo da Embrapa e sem motorista do SLT', max_length=255, verbose_name='Modalidade'),
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('number', models.CharField(max_length=50, unique=True, verbose_name='Número do Projeto')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Projeto')),
                ('responsible', models.CharField(blank=True, max_length=200, verbose_name='Responsável')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('funding_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='travel_requests.fundingagency', verbose_name='Agência Financiadora')),
            ],
            options={
                'verbose_name': 'Projeto de Pesquisa',
                'verbose_name_plural': 'Projetos de Pesquisa',
                'db_table': 'research_projects',
                'ordering': ['number'],
            },
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='travel_requests', to='travel_requests.researchproject', verbose_name='Projeto (Recurso)'),
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('from_status', models.CharField(max_length=20, verbose_name='De')),
                ('to_status', models.CharField(max_length=20, verbose_name='Para')),
                ('observation', models.TextField(blank=True, verbose_name='Observação')),
                ('email_sent', models.BooleanField(default=False, verbose_name='E-mail Enviado')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes_made', to='users.userprofile', verbose_name='Alterado por')),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='travel_requests.travelrequest', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Mudança de Status',
                'verbose_name_plural': 'Mudanças de Status',
                'db_table': 'travel_status_changes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelBeneficiary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('beneficiary_type', models.CharField(choices=[('EMPLOYEE', 'Empregado'), ('COLLABORATOR', 'Colaborador'), ('RELEASED', 'Liberado'), ('SPONSORED', 'Patrocinado'), ('EXTERNAL', 'Externo')], default='EMPLOYEE', max_length=20, verbose_name='Tipo de Favorecido')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('start_date', models.DateField(verbose_name='Início do Período')),
                ('end_date', models.DateField(verbose_name='Fim do Período')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('daily_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Qtde. Diárias')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor da Diária (R$)')),
                ('hotel_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hotel (R$)')),
                ('additional_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Adicionais (R$)')),
                ('sei_process', models.CharField(blank=True, max_length=25, verbose_name='Processo SEI')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='benefited_travels', to='users.userprofile', verbose_name='Perfil (interno)')),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='travel_requests.travelrequest', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Favorecido',
                'verbose_name_plural': 'Favorecidos',
                'db_table': 'travel_beneficiaries',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('expense_element', models.CharField(help_text='Ex.: 339014.14 — Diárias no País', max_length=20, verbose_name='Elemento de Despesa')),
                ('ugr', models.CharField(blank=True, max_length=12, verbose_name='UGR')),
                ('funding_source', models.CharField(blank=True, max_length=20, verbose_name='Fonte')),
                ('ptres', models.CharField(blank=True, max_length=12, verbose_name='PTRES')),
                ('pi', models.CharField(blank=True, max_length=30, verbose_name='PI (Plano Interno)')),
                ('commitment_number', models.CharField(blank=True, help_text='Ex.: 2026NE000123', max_length=30, verbose_name='Nota de Empenho')),
                ('adjusted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Ajustado (R$)')),
                ('beneficiary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='travel_requests.travelbeneficiary', verbose_name='Favorecido')),
            ],
            options={
                'verbose_name': 'Dotação Orçamentária',
                'verbose_name_plural': 'Dotações Orçamentárias',
                'db_table': 'budget_allocations',
            },
        ),
    ]
