# Generated by Django 5.0.4 on 2026-07-05 01:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0002_fundingagency_travelrequest_modality_researchproject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Linha de Recurso',
                'verbose_name_plural': 'Linhas de Recurso',
                'db_table': 'resource_lines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('document', models.CharField(blank=True, max_length=20, verbose_name='CNPJ/CPF')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Patrocinador',
                'verbose_name_plural': 'Patrocinadores',
                'db_table': 'sponsors',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='researchproject',
            name='is_external',
            field=models.BooleanField(default=False, verbose_name='Projeto Externo'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Saída'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='exceptionality_justification',
            field=models.TextField(blank=True, help_text='Obrigatória para viagem aérea solicitada com menos de 17 dias de antecedência.', verbose_name='Justificativa de Excepcionalidade'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='return_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Retorno'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='trip_type',
            field=models.CharField(blank=True, choices=[('CARGO_OUT', 'Transporte de carga fora do município'), ('PRIVATE_VEHICLE', 'Transporte de pessoas com veículo particular'), ('RENTED_OR_TAXI', 'Transporte de pessoas com veículo locado ou táxi'), ('EMBRAPA_WITH_SLT', 'Veículo da Embrapa com motorista do SLT'), ('EMBRAPA_NO_SLT', 'Veículo da Embrapa sem motorista do SLT'), ('AIR', 'Viagem aérea')], max_length=20, verbose_name='Tipo de Viagem'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='cost_type',
            field=models.CharField(choices=[('NO_COST_LOCAL', 'Sem custo — dentro do município'), ('EMBRAPA_COST', 'Com ônus da Embrapa'), ('EXTERNAL_PROJECT', 'Sem ônus da Embrapa — projeto externo'), ('SPONSOR', 'Sem ônus da Embrapa — patrocinador'), ('NO_EMBRAPA_COST', 'Sem Ônus para Embrapa (legado)')], default='EMBRAPA_COST', max_length=20, verbose_name='Tipo de Ônus'),
        ),
        migrations.CreateModel(
            name='FlightTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('origin', models.CharField(max_length=120, verbose_name='Origem')),
                ('destination', models.CharField(max_length=120, verbose_name='Destino')),
                ('flight_date', models.DateField(blank=True, null=True, verbose_name='Data do Voo')),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Estimado (R$)')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='travel_requests.travelbeneficiary', verbose_name='Favorecido')),
                ('travel_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='travel_requests.travelrequest', verbose_name='Viagem')),
            ],
            options={
                'verbose_name': 'Passagem',
                'verbose_name_plural': 'Passagens',
                'db_table': 'flight_tickets',
            },
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='resource_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='travel_requests', to='travel_requests.resourceline', verbose_name='Linha de Recurso'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='travel_requests', to='travel_requests.sponsor', verbose_name='Patrocinador'),
        ),
    ]
