# Generated by Django 5.0.4 on 2026-07-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0003_resourceline_sponsor_researchproject_is_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='itinerary',
            field=models.CharField(blank=True, help_text='Ex.: Cruz das Almas - Salvador - Brasília', max_length=255, verbose_name='Roteiro'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='transport_means',
            field=models.CharField(blank=True, choices=[('AIR', 'Aéreo'), ('GROUND', 'Terrestre'), ('OFFICIAL_VEHICLE', 'Veículo Oficial'), ('OWN_VEHICLE', 'Veículo Próprio')], max_length=20, verbose_name='Meio de Transporte'),
        ),
    ]
