# Generated by Django 5.0.4 on 2026-07-12 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0004_travelrequest_itinerary_travelrequest_observations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='Código (Plano de Ação)')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
            options={
                'verbose_name': 'Atividade de Pesquisa',
                'verbose_name_plural': 'Atividades de Pesquisa',
                'db_table': 'research_activities',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='research_ac_code_24d613_idx')],
            },
        ),
    ]
