# Generated by Django 5.0.4 on 2026-07-12 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0005_researchactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelrequest',
            name='transport_means',
            field=models.CharField(blank=True, choices=[('AIR', 'Aéreo'), ('AIR_ROAD', 'Aero/Rodoviário'), ('RIVER', 'Fluvial'), ('RIVER_ROAD', 'Fluvial/Rodoviario'), ('ROAD', 'Rodoviário')], max_length=20, verbose_name='Meio de Transporte'),
        ),
    ]
