# Generated by Django 5.0.4 on 2026-07-12 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0007_alter_travelrequest_transport_means'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAdvance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nature', models.CharField(choices=[('PROVEN_EXPENSES', 'Despesas comprovadas'), ('TICKETS', 'Passagens'), ('SERVICES', 'Serviços'), ('EVENT_FEE', 'Serviços - Taxa de inscrição em eventos')], max_length=20, verbose_name='Natureza')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor (R$)')),
                ('justification', models.TextField(blank=True, verbose_name='Justificativa')),
            ],
            options={
                'verbose_name': 'Outro Adiantamento',
                'verbose_name_plural': 'Outros Adiantamentos',
                'db_table': 'travel_advances',
            },
        ),
        migrations.AddField(
            model_name='researchactivity',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Saldo (R$)'),
        ),
        migrations.AddField(
            model_name='researchactivity',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Término'),
        ),
        migrations.AddField(
            model_name='researchactivity',
            name='responsible',
            field=models.CharField(blank=True, max_length=200, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='researchactivity',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Início'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='research_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='travel_requests', to='travel_requests.researchactivity', verbose_name='Atividade (Fonte de Recurso)'),
        ),
        migrations.AlterField(
            model_name='researchactivity',
            name='code',
            field=models.CharField(max_length=40, unique=True, verbose_name='Número (Plano de Ação)'),
        ),
        migrations.AlterField(
            model_name='researchactivity',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Título da Atividade'),
        ),
        migrations.AlterField(
            model_name='travelrequest',
            name='cost_type',
            field=models.CharField(choices=[('NO_COST_LOCAL', 'Sem custo — dentro do município'), ('EMBRAPA_COST', 'Com Ônus para Embrapa'), ('NO_ONUS', 'Sem Ônus para Embrapa'), ('EXTERNAL_PROJECT', 'Sem ônus da Embrapa — projeto externo'), ('SPONSOR', 'Sem ônus da Embrapa — patrocinador'), ('NO_EMBRAPA_COST', 'Sem Ônus para Embrapa (legado)')], default='EMBRAPA_COST', max_length=20, verbose_name='Tipo de Ônus'),
        ),
        migrations.AddIndex(
            model_name='researchactivity',
            index=models.Index(fields=['responsible'], name='research_ac_respons_afa493_idx'),
        ),
        migrations.AddField(
            model_name='traveladvance',
            name='travel_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='travel_requests.travelrequest', verbose_name='Viagem'),
        ),
    ]
