# Generated by Django 5.0.4 on 2026-07-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0008_traveladvance_researchactivity_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='sei_process',
            field=models.CharField(blank=True, max_length=25, verbose_name='Processo SEI'),
        ),
    ]
