# Generated by Django 5.0.4 on 2026-07-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0009_travelrequest_sei_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelrequest',
            name='commitment_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nota de Empenho'),
        ),
        migrations.AddField(
            model_name='travelrequest',
            name='committed_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Empenhado (R$)'),
        ),
    ]
