# Generated by Django 5.0.4 on 2026-07-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0010_travelrequest_commitment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveladvance',
            name='nature',
            field=models.CharField(choices=[('PROVEN_EXPENSES', 'Despesas comprovadas'), ('LODGING', 'Hospedagem'), ('URBAN_TRANSPORT', 'Deslocamento urbano'), ('SERVICES', 'Serviços'), ('EVENT_FEE', 'Serviços - Taxa de inscrição em eventos')], max_length=20, verbose_name='Natureza'),
        ),
    ]
