# Generated by Django 5.0.4 on 2026-07-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0011_alter_traveladvance_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelbeneficiary',
            name='bank_info',
            field=models.CharField(blank=True, max_length=120, verbose_name='Dados Bancários'),
        ),
        migrations.AddField(
            model_name='travelbeneficiary',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='travelbeneficiary',
            name='position',
            field=models.CharField(blank=True, max_length=120, verbose_name='Cargo'),
        ),
        migrations.AddField(
            model_name='travelbeneficiary',
            name='registration_number',
            field=models.CharField(blank=True, max_length=30, verbose_name='Matrícula'),
        ),
    ]
