# Generated by Django 5.0.4 on 2026-07-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_requests', '0012_travelbeneficiary_bank_info_travelbeneficiary_cpf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelbeneficiary',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
    ]
