# Generated by Django 5.0.4 on 2026-07-04 23:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travel_requests', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountabilityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('actual_departure_date', models.DateField(blank=True, null=True, verbose_name='Saída Efetiva')),
                ('actual_return_date', models.DateField(blank=True, null=True, verbose_name='Retorno Efetivo')),
                ('total_daily_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total de Diárias Recebido (R$)')),
                ('total_daily_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total de Diárias Devido (R$)')),
                ('other_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Outras Despesas Comprovadas (R$)')),
                ('trip_report', models.TextField(blank=True, verbose_name='Relatório de Viagem')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SUBMITTED', 'Enviada'), ('UNDER_REVIEW', 'Em Análise (SOF)'), ('APPROVED', 'Atestada'), ('CLOSED', 'Encerrada')], default='DRAFT', max_length=20, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada em')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Analisada em')),
                ('review_notes', models.TextField(blank=True, verbose_name='Observações da Análise')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountability_reviews', to='users.userprofile', verbose_name='Analisada por (SOF)')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accountability_reports', to='users.userprofile', verbose_name='Enviada por')),
                ('travel_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='accountability_report', to='travel_requests.travelrequest', verbose_name='Solicitação de Viagem')),
            ],
            options={
                'verbose_name': 'Prestação de Contas',
                'verbose_name_plural': 'Prestações de Contas',
                'db_table': 'accountability_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='accountabil_status_9c5663_idx')],
            },
        ),
    ]
