# Generated by Django 5.0.4 on 2026-07-13 20:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountabilityreport',
            name='advance_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Adiantamento Realizado (R$)'),
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('item_type', models.CharField(choices=[('LODGING', 'Hospedagem'), ('TICKETS', 'Passagens'), ('TAXI', 'Táxi'), ('TOLL_PARKING', 'Pedágio / Estacionamento'), ('SERVICES', 'Serviços'), ('FUEL', 'Combustível'), ('OTHER', 'Outros')], max_length=20, verbose_name='Tipo')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('proven_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Comprovado (R$)')),
                ('approved_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Aprovado (R$)')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_items', to='accountability.accountabilityreport', verbose_name='Prestação de Contas')),
            ],
            options={
                'verbose_name': 'Comprovação de Despesa',
                'verbose_name_plural': 'Comprovações de Despesa',
                'db_table': 'accountability_expense_items',
                'ordering': ['created_at'],
            },
        ),
    ]
