# Generated by Django 5.0.4 on 2026-07-19 12:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountability', '0002_accountabilityreport_advance_received_expenseitem'),
        ('users', '0005_favorecido_person_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountabilityreport',
            name='commitment_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nota de Empenho (PCV)'),
        ),
        migrations.CreateModel(
            name='AccountabilityRouting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('action', models.CharField(max_length=150, verbose_name='Natureza')),
                ('note', models.TextField(blank=True, verbose_name='Justificativa')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='accountability.accountabilityreport', verbose_name='Prestação de Contas')),
                ('responsible', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pcv_routings', to='users.userprofile', verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Encaminhamento da PCV',
                'verbose_name_plural': 'Histórico de Encaminhamento',
                'db_table': 'accountability_routings',
                'ordering': ['created_at'],
            },
        ),
    ]
