# Generated by Django 5.0.4 on 2026-07-04 23:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('config_key', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('config_value', models.CharField(max_length=255, verbose_name='Valor')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'db_table': 'system_config',
                'ordering': ['config_key'],
            },
        ),
    ]
